### PR TITLE
Add flask-migrate to enable database migration

### PR DESCRIPTION
**Pull request by mschader**
This will add functionability to create database migrations. The concept was taken from:
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database

### CODE REVIEW

**Comment by fleaz** [comment]
So hyped to get DB migrations. No more manual fiddeling around in the prod DB via cli :D

Will this happen automatically or do we have to write migration scripts?

**Comment by mschader** [comment]
As far as i understood, these changes will be sufficient to initially crate the migrations structural folder and upgrade the database by simply using `flask db <command>` (e.g. `flask db upgrade`) 

You are even able to only select single tables to migrate and stuuff like moving forward/backward in versions.

**Comment by fleaz** [comment]
The failing TravisCI tests are a bug in pipenv--> [#3026](https://github.com/pypa/pipenv/issues/3026)

**Comment by mschader** [comment]
I would suggest to merge this branch already into development so we can start using it as soon as #19 is finished.

**Comment by fleaz** [comment]
Made a squash merge because this feature branch contained strange commits because the branch was created from master instead of development.

Thanks!

**Pull request merged**
